[[main]]
name = "Start"
pageRef = "/"
weight = 10
[[main]]
name = "Posten"
pageRef = "/posts"
weight = 20

[[footer]]
name = "Kategorien"
pageRef = "/categories"
weight = 10
[[footer]]
name = "Tags"
pageRef = "/tags"
weight = 20
