[[main]]
name = "Asosiy"
pageRef = "/"
weight = 10
[[main]]
name = "Men Haqimda"
pageRef = "/about"
weight = 20
[[main]]
name = "Maqolalar"
pageRef = "/articles"
weight = 30

[[footer]]
name = "Kategoriyalar"
pageRef = "/categories"
weight = 10
[[footer]]
name = "Teglar"
pageRef = "/tags"
weight = 20
