[[main]]
name = "Main"
pageRef = "/"
weight = 10
[[main]]
name = "About Me"
pageRef = "/about"
weight = 20
[[main]]
name = "Articles"
pageRef = "/articles"
weight = 30

[[footer]]
name = "Categories"
pageRef = "/categories"
weight = 10
[[footer]]
name = "Tags"
pageRef = "/tags"
weight = 20
