[[main]]
name = "Основная"
pageRef = "/"
weight = 10
[[main]]
name = "Про меня"
pageRef = "/about"
weight = 20
[[main]]
name = "Статьи"
pageRef = "/articles"
weight = 30

[[footer]]
name = "Категории"
pageRef = "/categories"
weight = 10
[[footer]]
name = "Теги"
pageRef = "/tags"
weight = 20
