[[main]]
name = "Start"
pageRef = "/"
weight = 10
[[main]]
name = "Über Mich"
pageRef = "/about"
weight = 20
[[main]]
name = "Artikel"
pageRef = "/articles"
weight = 30

[[footer]]
name = "Kategorien"
pageRef = "/categories"
weight = 10
[[footer]]
name = "Tags"
pageRef = "/tags"
weight = 20
