[[main]]
name = "Main"
pageRef = "/"
weight = 10
[[main]]
name = "Posts"
pageRef = "/posts"
weight = 20

[[footer]]
name = "Categories"
pageRef = "/categories"
weight = 10
[[footer]]
name = "Tags"
pageRef = "/tags"
weight = 20
