title = "Kei Lambda"
baseURL = "https://blog.keilambda.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[permalinks]
articles = "/articles/:year/:month/:day/:slug"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = "modus-vivendi"
tabWidth = 4
